### PR TITLE
Wip/hughsie/priority

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
screenshot from 2018-02-14 12-24-15

**Comment by superm1** [comment]
I think you also want to automatically want to put QA level issues higher priority than LVFS wide issues.  Eg if there is a more specific problem that needs to be matched.

**Comment by hughsie** [comment]
You could argue the opposite, surely? That admin issues trump all others? With the shared priority model we have in this PR you can "negotiate" with the admin if a specific ordering is required.

**Comment by superm1** [comment]
Yeah I guess you could argue both ways, let's see how it works and can raise issues if necessary as usage goes up.

**Pull request merged**
