### PR TITLE
Show a detailed component requirement view when required

### PR DESCRIPTION
**Pull request by hughsie**
For the uncommon case of a firmware with a GUID requirement, or where a version
range is required switch to an 'advanced' table view that allows the user to
both view all existing requirements and to add more.

Fixes https://github.com/hughsie/lvfs-website/issues/221

### CODE REVIEW

**Comment by hughsie** [comment]
screenshot from 2019-01-03 16-16-46

**Comment by superm1** [comment]
When "Hardware" is selected I think you need to prevent choosing some of the compare types and any values in the version field.

Or alternatively don't allow adding "hardware" here to avoid that set of bad values happening.

**Comment by hughsie** [comment]
> I think you need to prevent choosing some of the compare types and any values in the version field

I think we need `ne` too -- although I agree `lt` and `ge` don't make a lot of sense for GUIDs.

**Comment by hughsie** [comment]
> I think we need ne too

Actually, that's nonsense. CHIDs have to just be specified as OR text.

**Comment by hughsie** [comment]
Okay, reworked to split out each as sections. 

screenshot from 2019-01-08 15-22-36

This works a lot better as you can put the right kind of placeholder in each section...

**Pull request merged**
