### PR TITLE
Autodelete duplicate firmware uploaded by robots

### PR DESCRIPTION
**Pull request by hughsie**
Fixes: https://github.com/hughsie/lvfs-website/issues/143

110% untested.

### CODE REVIEW

**Comment by superm1** [comment]
Looks good to me, if you want to put it on staging and mark the thunderbolt user as a robot on staging I'll give it a test run. (My Oauth manager account can't log into staging IIRC to do this).

**Comment by hughsie** [comment]
Both done.

**Comment by superm1** [comment]
I'm getting 502 errors both from uploader script on staging and trying to login from browser.

**Comment by hughsie** [comment]
Urgh, the same issue we had on production a few days ago. Fixed, sorry.

**Comment by superm1** [comment]
Seems passing `auto-delete` isn't working still.

Passing like this:

``` 
r = requests.post(uri, data={"target": target, "auto-delete" : "true"},
                                   files={'file': f},
                                   cookies=self.cookies)
```

And still getting `Failed to upload file: A file with hash ...`

**Comment by hughsie** [comment]
> And still getting Failed to upload file: A file with hash ...

Right, as expected. If you change the description in the metainfo, recompress the .cab file, then submit it should auto-delete; there is no point deleting firmware `foo` and then re-uploading the exact same firmware `foo` -- I thought the requirement was for firmware that had changed without bumping the version number...

**Comment by superm1** [comment]
> Right, as expected. If you change the description in the metainfo, recompress the .cab file, then submit it should auto-delete; there is no point deleting firmware foo and then re-uploading the exact same firmware foo -- I thought the requirement was for firmware that had changed without bumping the version number...

Oh duh - sorry brain fart in my testing.  I changed a bit in the firmware, rebuilt the CAB an re-uploaded and it worked properly, saw the old file deleted and new one created.

**Comment by hughsie** [comment]
Ahh, good, thanks for testing. I've added an eventlog item (as well as the existing `FirmwareEvent`) so that the admin knows what's happened. I'm also wondering if we want to actually delete (rather than archive) when we have a large number of "archived" firmwares. In which case, it might be good to add metadata to the firmware to say that it was autodeleted due to a better version coming up, and put those first in line to be deleted.

I also think we want to add a check to the autodelete that the firmware is indeed in embargo or private, correct? I suppose returning with a error if we tried to autodelete something in a public remote is the right thing to do, right?

**Comment by superm1** [comment]
> Ahh, good, thanks for testing. I've added an eventlog item (as well as the existing FirmwareEvent) so that the admin knows what's happened. I'm also wondering if we want to actually delete (rather than archive) when we have a large number of "archived" firmwares. In which case, it might be good to add metadata to the firmware to say that it was autodeleted due to a better version coming up, and put those first in line to be deleted.

That's good on the events.  Actually I think auto-deleted firmware doesn't need to stay around at all.  I think it should be permanently removed.  The use case for it is such that if tests failed, the build is rerun until they pass.  You only want the "latest" of that "version".

> I also think we want to add a check to the autodelete that the firmware is indeed in embargo or private, correct? I suppose returning with a error if we tried to autodelete something in a public remote is the right thing to do, right?

Robots by definition shouldn't be able to demote firmware, but I guess that's a good safeguard to keep in place.

**Comment by hughsie** [comment]
> I think it should be permanently removed

If that's the case then I think we need to be a lot more careful about matching old firmwares and thinking about things like OEM and ODM ownership and who gets to permanently delete firmware, especially when potentially "owned" by someone else.

**Comment by superm1** [comment]
I think to me only robots should be able to do this and only to firmware they uploaded.  That should help prevent cross oem/odm contamination.

**Comment by hughsie** [comment]
I've rebased the patch. I'm not sure if permanently deleting is a good idea; we need the firmware archives for audit reasons and they'll be referenced in the metadata until the server cron job runs, and the user downloads new metadata. I'm fairly happy with the current patch, so I'm happy to deploy that with your blessing.

**Comment by hughsie** [comment]
I'll deploy this at the weekend -- thanks for the review.

**Comment by hughsie** [comment]
I've just deployed this. Yell if there are any problems.

**Pull request merged**
