### PR TITLE
Add support for signing firmware using Sigul

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/hughsie/lvfs-website/issues/87

### CODE REVIEW

**Comment by superm1** [comment]
No test suite, i'm guessing since it would add a new dependency on lvfs-website?

**Comment by hughsie** [comment]
Well, we'd have to mock-up the sigul command line, so I didn't see much point. Other ideas welcome.

**Comment by superm1** [comment]
Can you deploy a sigul instance with a test key?  Maybe not worth the effort though.  Otherwise looks fine by me.

**Comment by hughsie** [comment]
> Can you deploy a sigul instance with a test key

Dude, it took me a day to deploy Sigul on my local system and have it half work. :)

**Pull request merged**
