### PR TITLE
Automatically demote firmware with >5 failures and a success rate of <70%

### PR DESCRIPTION
**Pull request by hughsie**
This was requested by Intel.

### CODE REVIEW

**Comment by hughsie** [comment]
Screenshot from 2019-06-06 12-12-07

**Comment by superm1** [comment]
In principle this seems like a really sensible thing to do.  I do like that it would only be marked for failures, so it would encourage marking known issues if there are known issues.  I have to start to worry though that this could cause a bad actor to "game" the automatic downgrade system.   If they could make 50 bad reports automatically generated with random machine IDs be uploaded from a script that would trigger this, wouldn't it?

**Comment by hughsie** [comment]
> this could cause a bad actor to "game" the automatic downgrade system

It could, yes. I do think that's somewhat unlikely, and if that happened we could certainly put in limit on the client IP address or even disable it for specific firmwares were required.

**Comment by hughsie** [comment]
Lets give this a go, and if it gets abused we can turn it off easily.

**Comment by superm1** [comment]
Sounds good.

**Pull request merged**
