### PR TITLE
trivial: Try to convince people to use the testing target

### PR DESCRIPTION
**Pull request by hughsie**
Show a warning when trying to promote a firmware into stable that has spent
less than a day in testing.

### CODE REVIEW

**Comment by superm1** [comment]
I'd argue you should also let time in the embargo target also count for this.

**Comment by hughsie** [comment]
It's tricky as embargo is only available to the vendor, so the number of testers are going to be counted on one hand. Maybe we can tie in the number of downloads too?

**Comment by superm1** [comment]
At least with our use on uefi the testing is mostly done offline before it even hits LVFS. I'd think that mirrors at least some other vendors use too.

**Comment by superm1** [comment]
Once reports are coming in more consistently (maybe after next Ubuntu and Fedora releases out) could be to only put in testing and automatically promote to stable after some X number of reports with at least Y% stable. Or vice versa to pull back to testing after so many failed reports with an email / issue to say go investigate why there are so many failures.

**Comment by hughsie** [comment]
Okay, I've scaled back this down to just informational -- you're right we can do something better when the reports are flooding in.

**Pull request merged**
