### PR TITLE
Wip/hughsie/theme

### PR DESCRIPTION
**Pull request by hughsie**
This is an unfinished sneak preview, comments most welcome -- you can play with a full mirror on https://staging.fwupd.org/

### CODE REVIEW

**Comment by superm1** [comment]
At least on mobile version of theme all the menus to interact seem to be hiding. There's a hidden button in the top right corner.

Screenshot demonstration:
https://photos.app.goo.gl/ATauojLmJJ57F8aG8

**Comment by superm1** [comment]
I can't really poke around too much since I'm logging in with azure though..

**Comment by hughsie** [comment]
> since I'm logging in with azure though..

can i switch your staging account to have a password?

**Comment by superm1** [comment]
> can i switch your staging account to have a password?
That or I can grab one of the robot passwords and log in as a robot.  What's more useful to you to have feedback as?

At least in unlogged in form:
* I notice this page wraps wrong: https://staging.fwupd.org/lvfs/device/c0745fac-f5a5-46c9-b716-3cc5781e876e
* This old logo doesn't really fit with the new look in my opinion: https://staging.fwupd.org/lvfs/docs/introduction
* Putting apply for new account in this page makes me have an expectation that it's actually an email form or POST form or something similar: https://staging.fwupd.org/lvfs/login1

**Comment by hughsie** [comment]
> What's more useful to you to have feedback as?

Both :) Lets got robots first, and then I can add you if that helps.

**Comment by superm1** [comment]
Looks like this page is wrapping wrong:
https://staging.fwupd.org/lvfs/docs/metainfo/style

The sign in dashboard downloads white against blue gradiant colors seems a bit hard to read to me and stand out a lot compared to the theme.

The tests page the red on green is also hard contrast to interpret unless you highlight it.

Release notes page is wrapping poorly.

I'd really like to see device/component breadcrumb move to the top of pages if possible.

Running search on pages is unclear what it should do.  I tried putting in some searches and it just reloaded the page.

**Comment by superm1** [comment]
I notice logging out the flashed message blocks the UX.
image

**Comment by hughsie** [comment]
I think I've fixed all of those. There are much better filters for firmware in the menu now (e.g. all in embargo) and you can even use the internal search bar for things like "xps 13" to show all firmware versions for a specific model. It's much more intuitive, and if you agree, I think it means we can remove the single-state-for-device filter view completely.

**Comment by superm1** [comment]
I do like the new filters in the firmware menu.  That does allow the page to load a lot more quickly.  Between search box and those filters I don't think we really need a "whole view" page anymore, I agree.

It looks to me like https://staging.fwupd.org/lvfs/firmware is showing more than just Dell firmware (at least logged in as a robot).

I think it would be useful to watermark the search box with "Search Firmware" since it's not going to pull up the documentation pages.

**Comment by hughsie** [comment]
I've pushed the latest version with a lot of the fixes we've talked about. More feedback very welcome, thanks!

**Comment by superm1** [comment]
I don't see anything else standing out from my robot account, I think it looks really good.

**Comment by hughsie** [comment]
This pull request **introduces 2 alerts** when merging 64eec37debc45edec8be36fcdd138480f29f6b78 into bd4525bdb0375ffed0f2842ff006a9cdcec25868 - [view on LGTM.com](https://lgtm.com/projects/g/hughsie/lvfs-website/rev/pr-2683820e7f4bdd2b7cf4783072795b7d26fe0c7f)

**new alerts:**

* 2 for Duplicate HTML element attributes

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by hughsie** [comment]
This pull request **introduces 2 alerts** when merging 462728bedd272edd95eaaab6b5d6526f99728228 into bd4525bdb0375ffed0f2842ff006a9cdcec25868 - [view on LGTM.com](https://lgtm.com/projects/g/hughsie/lvfs-website/rev/pr-d905b998a93a2deb7e0b98b557b20e454a907a6e)

**new alerts:**

* 2 for Duplicate HTML element attributes

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
