### PR TITLE
Allow uploading duplicate components in composite firmwares

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/hughsie/lvfs-website/issues/122

I've pushed this to staging, can you test please?

### CODE REVIEW

**Comment by superm1** [comment]
Yes confirmed it works on staging for me.  Looks good.

**Comment by superm1** [comment]
Some more checks and I noticed the "delete" button isn't working.
`The LVFS is temporarily unavailable and should be back soon.`

**Comment by hughsie** [comment]
> I noticed the "delete" button isn't working.

Incorrect permissions on a directory just on the staging instance. Should be fixed now.

**Comment by hughsie** [comment]
Do you need this on the main instance ASAP or can it wait until Sunday?

**Comment by superm1** [comment]
It can wait.  This is just very early testing.

**Pull request merged**
