### PR TITLE
Wip/hughsie/flask migrate

### PR DESCRIPTION
**Pull request by hughsie**
This makes it easier to deploy without SSH access...

### CODE REVIEW

**Comment by superm1** [comment]
Nothing stands out to me with this, but admittedly I don't know most of it :)

**Comment by hughsie** [comment]
I'd like to run this on the testing server before it merges with master, but I'l wait for the OAuth stuff to be confirmed to avoid complicating things.

**Comment by superm1** [comment]
The OAuth stuff is really close.  I think the only remaining problems are cosmetic now.

**Comment by hughsie** [comment]
Okay, running a modified version of this cleaned up the database considerably. Merged, thanks.

**Pull request closed without merging**
