### PR TITLE
Allow uploading by default to embargo for some vendors

### PR DESCRIPTION
**Pull request by hughsie**
Fixes: https://github.com/hughsie/lvfs-website/issues/100

### CODE REVIEW

**Comment by superm1** [comment]
Looks fine to me.  can you push it to staging and i'll confirm it works there?

**Comment by hughsie** [comment]
Done. I've set up dell to be embargo-by-default there too.

**Comment by hughsie** [comment]
I wasn't sure about that; the new key is `is_embargo_default` rather than `disallow_using_private_target` -- do you want to prevent the use of private completely? I suppose there's now a delete/undelete action if you want to remove the firmware from the dell embargo remote for a short time.

**Comment by superm1** [comment]
Yeah that was exactly my thought too, private really doesn't provide anything more than "delete" does.

**Pull request merged**
