### PR TITLE
Do not try to re-sign firmware referenced from multiple metainfo files

### PR DESCRIPTION
**Pull request by hughsie**
Fixes: https://github.com/hughsie/lvfs-website/issues/49

### CODE REVIEW

**Comment by superm1** [comment]
While fixing this, I think it would also be useful to adjust the 50x error page to show more about what was causing the failure (for the next issue that is to come up for example).

**Comment by hughsie** [comment]
You mean leaking the stack trace? That's usually frowned upon, and it's in the wsgi logs anyway.

**Comment by hughsie** [comment]
Okay, new code deployed to fwupd.org now too.

**Comment by superm1** [comment]
Oh as long as you're logging it somewhere useful, that's what's most important.

**Pull request merged**
