### PR TITLE
Send an email to the admin on critical failure

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by superm1** [comment]
LGTM, all comes down to how much you tag as critical for how annoying that gets :)

**Comment by PearsonWeng** [comment]
Hi Richard,
Seems server sent mail to admin only when critical failure found.
Could you please sent mail to the user who uploaded the firmware too.

**Comment by hughsie** [comment]
Hi @PearsonWeng  -- the critical error here refers to the python backtrace that the webservice produces; this isn't the kind of thing the uploader should have to deal with. Can you explain a little on which critical error you mean? Is there for instance an internal error or warning when you upload a broken cab file?

**Comment by PearsonWeng** [comment]
Hi Richard,
Sorry for my misunderstanding.
I'd like to the server can sent mail to uploader when then firmware was pulled back from stable to testing by server due to failures are report by end user.

For example, the firmware was pulled back to testing on 20200114, but I Did not receive the notification mail. So I can't take action immediately.

TimestampUserTarget
2020-04-22 07:16:32pearson_weng@compal.comstable
2020-01-14 10:11:19anon@fwupd.orgtesting
2019-11-19 07:25:39pearson_weng@compal.comstable
2019-11-08 09:35:19pearson_weng@compal.comembargo-lenovo_thinkpad

https://fwupd.org/lvfs/firmware/3109


取得 Android 版 Outlook<https://aka.ms/ghei36>
________________________________

**Comment by hughsie** [comment]
@PearsonWeng  I think it should have done that already; do you have the notify-demote-failures flag set in your profile? You can toggle it in the same place you change your profile password.

**Comment by PearsonWeng** [comment]
Thanks for your prompt support, seems I did not set the  notify-demote-failures flag.
Sorry again for my stupid question..

?? Android ? Outlook<https://aka.ms/ghei36>

________________________________

**Comment by hughsie** [comment]
> Sorry again for my stupid question..

There are no stupid questions, only insufficient documentation :)

**Pull request merged**
